### PR TITLE
Issue202 dentistry faq page - https://www.sunstar-foundation.org/dentistry/faq

### LINKED ISSUE #202: Dentistry FAQ page - https://www.sunstar-foundation.org/dentistry/faq

### PR DESCRIPTION
**Pull request by meejain**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes #202 

Test URLs:
- Original: https://www.sunstar-foundation.org/dentistry/faq
- Before: https://main--sunstar-foundation--hlxsites.hlx.live/dentistry/faq
- After: https://issue202-dentistry-faq--sunstar-foundation--hlxsites.hlx.live/dentistry/faq

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
 For e.g. cards | [doc-link](https://main--sunstar-foundation--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=0)

- [ ] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 For e.g. cards (grid)  | [doc-link](https://main--sunstar-foundation--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)

### CODE REVIEW

**Comment by JiangLong2019** [comment]
Some comments:

1. Need padding in mobile view
image

2. Nit: maybe it looks comfortable that keep the color ground of the title the same as the original site 

Original site:
image

EDS:
image

**Comment by meejain** [comment]
> Some comments:
> 
> 1. Need padding in mobile view
> 
> image
> 2. Nit: maybe it looks comfortable that keep the color ground of the title the same as the original site
> 
> Original site: image
> 
> EDS: image

Fixed now -

**Comment by meejain** [comment]
image

**Comment by JiangLong2019** [comment]
Hi @meejain maybe we are looking at diffferent urls, on this page https://issue202-dentistry-faq--sunstar-foundation--hlxsites.hlx.live/dentistry/faq I still can see some titles are missing padding, such as "よくある質問", "診療について". How about your side?

image

**Comment by meejain** [comment]
> Hi @meejain maybe we are looking at diffferent urls, on this page https://issue202-dentistry-faq--sunstar-foundation--hlxsites.hlx.live/dentistry/faq I still can see some titles are missing padding, such as "よくある質問", "診療について". How about your side?
> 
> image

Added "padded" to the section to have it all across with consistency - 

image

**Review by bosschaert — APPROVED** [review]

**Pull request merged**
