### PR TITLE
Migrate "native-image-sizes" & Forms Variants from sunstar.com

### LINKED ISSUE #206: Migrate Varians from sunstar.com
Can you please migrate the following variants from sunstar.com:

1. Columns block:
- Flex start (this variant not needed if we can control it via markdown with vertical align in word)
- Native Image Sizes
- no padding

2. Containers
- Narrower

### PR DESCRIPTION
**Pull request by shrotia**
Fixes #206

Test URLs:
- Original: https://www.sunstar-foundation.org/en/about-us/hiroo-kaneda-grant
- Before: https://main--sunstar-foundation--hlxsites.hlx.live/en/about-us/hiroo-kaneda-grant
- After: https://issue-206--sunstar-foundation--hlxsites.hlx.live/en/about-us/hiroo-kaneda-grant

- [x] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 Columns (native-image-sizes)  | [doc-link](https://issue-206--sunstar-foundation--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/columns&index=5)
 Forms (narrower)  | [doc-link](https://issue-206--sunstar-foundation--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/forms&index=1)
 Columns (Left Aligned native image)  | [doc-link](https://issue-206--sunstar-foundation--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/columns&index=6)

### CODE REVIEW

**Comment by JiangLong2019** [comment]
@shrotia Seems the changes happen on Column block but I cannot find it on the test page. Could you confirm if the test url?

**Comment by shrotia** [comment]
> @shrotia Seems the changes happen on Column block but I cannot find it on the test page. Could you confirm the test url?

Thanks for reviewing @JiangLong2019 , this PR was not against any webpage, @ehrro raised this issue https://github.com/hlxsites/sunstar-foundation/issues/206 to migrate the variants/changes from sunstar.com to sunstar-foundation. 
I have added variants in the Block Library for the visual review.

**Comment by JiangLong2019** [comment]
@shrotia Okay, I just wonder how to test them ^ ^

**Comment by shrotia** [comment]
> @shrotia Okay, I just wonder how to test them ^ ^

Yes right, I agree with your concern. @ehrro do you have any pages where these proposed variations might be utilized? This way, we can test them while porting.

**Comment by shrotia** [comment]
PSI score is fine when checked on Google PSI portal (tried multiple times). [link](https://pagespeed.web.dev/analysis/https-issue-206--sunstar-foundation--hlxsites-hlx-live-en-about-us-hiroo-kaneda-grant/d8qiadhh45?form_factor=mobile)

image

**Review by ehrro — APPROVED** [review]

**Comment by shrotia** [comment]
> Details

ah it was giving low PSI for block library links

**Pull request merged**
