### PR TITLE
Add changes for researchreport pages

### PR DESCRIPTION
**Pull request by RitwikSrivastava**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes #<gh-issue-id>

Test URLs:
- Original: https://www.sunstar-foundation.org/grants/research-report
- Before: https://main--sunstar-foundation--hlxsites.hlx.live/grants/research-report
- After: https://pdfcolumn--sunstar-foundation--hlxsites.hlx.live/grants/research-report

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
 For e.g. cards | [doc-link](https://main--sunstar-foundation--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=0)

- [ ] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 For e.g. cards (grid)  | [doc-link](https://main--sunstar-foundation--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)

### CODE REVIEW

**Comment by bosschaert** [comment]
The table still looks quite different on the test URL page:

Original:
Screenshot 2024-01-17 at 10 42 53

This branch:
Screenshot 2024-01-17 at 10 42 58

**Comment by JiangLong2019** [comment]
In mobile view, there are some details things like padding and space that need to be checked.

Original site:
image

EDS site:
image

**Comment by RitwikSrivastava** [comment]
@bosschaert Can you please re-review ?

**Comment by bosschaert** [comment]
@RitwikSrivastava could you please confirm that the reported visual changes are no issue?

**Comment by RitwikSrivastava** [comment]
@bosschaert As all the style changes are for orderedtext variant, I can confirm that the reported visual changes are not an issue. I have checked those also.

**Pull request merged**
