### PR TITLE
Breadcrumb Changes wrt to redirect pages

### PR DESCRIPTION
**Pull request by jindaliiita**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes 

Test URLs:
- Original: https://www.sunstar-foundation.org/archives/dentistry/news/%e3%80%90%e6%9c%80%e6%96%b0%e3%80%91%e5%8f%b0%e9%a2%a814%e5%8f%b7%e3%81%ab%e3%82%88%e3%82%8b%e8%a8%ba%e7%99%82%e3%81%b8%e3%81%ae%e5%bd%b1%e9%9f%bf%e3%81%ab%e3%81%a4%e3%81%84%e3%81%a6
- Before: https://main--sunstar-foundation--hlxsites.hlx.live/archives/dentistry/news/20220920
- After: https://breadcrumb-changes--sunstar-foundation--hlxsites.hlx.live/archives/dentistry/news/20220920

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
 For e.g. cards | [doc-link](https://main--sunstar-foundation--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=0)

- [ ] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 For e.g. cards (grid)  | [doc-link](https://main--sunstar-foundation--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)

### CODE REVIEW

**Comment by jindaliiita** [comment]
I am not sure if this is the right way to handle these type of cases

**Comment by JiangLong2019** [comment]
A simple idea is that remove /archives directory from sharepoint to keep all in the same directory level, and add redirection 
/archives/dentistry/news/* → /dentistry/news/*
 What do you think?

**Comment by jindaliiita** [comment]
> A simple idea is that remove /archives directory from sharepoint to keep all in the same directory level, and add redirection /archives/dentistry/news/* → /dentistry/news/* What do you think?

Yes, apart from this, I also don't see any other alternative.
@sdmcraft @bosschaert Your thoughts on this ?

**Comment by bosschaert** [comment]
> Yes, apart from this, I also don't see any other alternative. This issue is also present on [experience pages](https://main--sunstar-foundation--hlxsites.hlx.page/experience/576). @sdmcraft @bosschaert @ehrro Your thoughts on this ?

Sounds reasonable to me. The URL of the dentistry news articles is changing anyway because of the Japanese characters in the URL which has now become a date.

**Review by bosschaert — APPROVED** [review]

**Comment by jindaliiita** [comment]
> > Yes, apart from this, I also don't see any other alternative. This issue is also present on [experience pages](https://main--sunstar-foundation--hlxsites.hlx.page/experience/576). @sdmcraft @bosschaert @ehrro Your thoughts on this ?
> 
> Sounds reasonable to me. The URL of the dentistry news articles is changing anyway because of the Japanese characters in the URL which has now become a date, so we could maybe just put them in /dentistry/news in the first place.

True but there are other cases also like [experience pages](https://main--sunstar-foundation--hlxsites.hlx.page/experience/576)

**Comment by jindaliiita** [comment]
> * : [https://breadcrumb-changes--sunstar-foundation--hlxsites.hlx.live](https://breadcrumb-changes--sunstar-foundation--hlxsites.hlx.live/archives/dentistry/news/20220920)

@ehrro Can you please confirm
Whether we can move /archives/dentistry/news/* pages to /dentistry/news/*
And /experience/* pages to /grants/experience/*

**Comment by ehrro** [comment]
Hello @jindaliiita yes I confirm you can move it from archive. Thank you.

**Comment by jindaliiita** [comment]
Closing this PR as changes are not needed

**Pull request closed without merging**
